game:
    player_count: 8
    day_max_speeches_per_player: 2
    roles:
        mafia: 2
        police: 1
        doctor: 1
        citizen: 4

llm:
    provider: openrouter
    models:
        - name: trinity-large-preview
          model: arcee-ai/trinity-large-preview:free
          count: 2
        - name: glm-4.5-air
          model: z-ai/glm-4.5-air:free
          count: 3
        - name: solar-pro-3
          model: upstage/solar-pro-3:free
          count: 3
